import {Translations} from "./schema";

export default {
  "404.message": "Die angeforderte Seite wurde nicht gefunden.",
  "500.message":
    "Ein unerwarteter Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.",
  "account.forgot_password": "Passwort vergessen",
  "account.login": "Anmelden",
  "account.password.reset": "Passwort zurücksetzen",
  "account.register": "Registrieren",
  "address.billing.title": "Rechnungsadresse",
  "address.shipping.title": "Lieferadresse",
  "cart.empty": "Ihr Warenkorb ist derzeit leer.",
  "cart.item_added": "Artikel in den Warenkorb gelegt!",
  "cart.view_cart": "Warenkorb ansehen",
  coming_soon: "Demnächst verfügbar!",
  "common.hello": "Hallo!",
  "common.logout": "Abmelden",
  "common.search": "Suche",
  "common.settings": "Einstellungen",
  "common.welcome": "Willkommen bei {{name}}!",
  "contact.form.email": "Ihre E-Mail",
  "contact.form.message": "Ihre Nachricht",
  "contact.form.name": "Ihr Name",
  "contact.form.send": "Nachricht senden",
  "download.file": "Datei herunterladen",
  "error.generic":
    "Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.",
  "feature.highlighted": "Hervorgehobenes Feature: {{description}}",
  "filter.by_category": "Nach Kategorie filtern",
  "filter.by_price": "Nach Preis filtern",
  "filter.clear_all": "Alle Filter löschen",
  "image.alt_text": "Bildbeschreibung",
  "navigation.about": "Über uns",
  "navigation.contact": "Kontakt",
  "navigation.explore": "Entdecken",
  "navigation.home": "Startseite",
  "order.confirmation": "Vielen Dank für Ihre Bestellung!",
  "order.details.order_number": "Bestellnummer: {{number}}",
  "order.details.placed_on": "Aufgegeben am: {{date}}",
  "order.details.title": "Bestelldetails",
  "pagination.next": "Weiter",
  "pagination.previous": "Zurück",
  "payment.information.title": "Zahlungsinformationen",
  "payment.method.credit_card": "Kreditkarte",
  "payment.method.debit_card": "Debitkarte",
  "payment.method.paypal": "PayPal",
  "product.add_to_cart": "In den Warenkorb",
  "product.details.description": "Beschreibung",
  "product.details.specifications": "Spezifikationen",
  "product.details.title": "Produktdetails",
  promotional_message: "Befristetes Angebot! Erhalten Sie {{discount}}% Rabatt",
  "review.placeholder": "Teilen Sie Ihre Meinung mit...",
  "review.rating.average": "Durchschnittlich",
  "review.rating.excellent": "Ausgezeichnet",
  "review.rating.good": "Gut",
  "review.rating.poor": "Schlecht",
  "review.rating.terrible": "Schrecklich",
  "review.title": "Schreiben Sie eine Bewertung",
  "search.no_results": "Für Ihre Suche wurden keine Ergebnisse gefunden.",
  "search.placeholder": "Nach Produkten suchen...",
  "shipping.flat_rate": "Pauschal Versand: {{price}}",
  "shipping.free_shipping": "Kostenloser Versand",
  "status.in_stock": "Auf Lager",
  "status.out_of_stock": "Nicht auf Lager",
  "success.message": "Ihre Anfrage war erfolgreich!",
  "tutorial.step": "Schritt {{number}}: {{instruction}}",
  "upload.file": "Datei hochladen",
  "user.profile.edit": "Profil bearbeiten",
  "user.profile.picture": "Profilbild",
  "user.profile.title": "Ihr Profil",
  "validation.invalid_email":
    "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
  "validation.password_mismatch": "Passwörter stimmen nicht überein.",
  "validation.required_field": "Dieses Feld ist erforderlich.",
  "wishes.happy_birthday": "Alles Gute zum Geburtstag, {{name}}!",
} satisfies Translations;