import { HugeTranslations } from "./huge.schema";

export default {
  "404.message": "The page you requested could not be found.",
  "500.message": "An unexpected error occurred. Please try again later.",
  "account.forgot_password": "Forgot Password",
  "account.login": "Login",
  "account.password.reset": "Reset Password",
  "account.register": "Register",
  "address.billing.title": "Billing Address",
  "address.shipping.title": "Shipping Address",
  "cart.empty": "Your cart is currently empty.",
  "cart.item_added": "Item added to cart!",
  "cart.view_cart": "View Cart",
  coming_soon: "Coming Soon!",
  "common.hello": "Hello!",
  "common.logout": "Log out",
  "common.search": "Search",
  "common.settings": "Settings",
  "common.welcome": "Welcome to {{name}}!",
  "contact.form.email": "Your Email",
  "contact.form.message": "Your Message",
  "contact.form.name": "Your Name",
  "contact.form.send": "Send Message",
  "download.file": "Download File",
  "error.generic": "An error occurred. Please try again later.",
  "feature.highlighted": "**Highlighted Feature:** {{description}}",
  "filter.by_category": "Filter by Category",
  "filter.by_price": "Filter by Price",
  "filter.clear_all": "Clear All Filters",
  "image.alt_text": "Image Description",
  "navigation.about": "About Us",
  "navigation.contact": "Contact",
  "navigation.explore": "Explore",
  "navigation.home": "Home",
  "order.confirmation": "Thank you for your order!",
  "order.details.order_number": "Order Number: {{number}}",
  "order.details.placed_on": "Placed on: {{date}}",
  "order.details.title": "Order Details",
  "pagination.next": "Next",
  "pagination.previous": "Previous",
  "payment.information.title": "Payment Information",
  "payment.method.credit_card": "Credit Card",
  "payment.method.debit_card": "Debit Card",
  "payment.method.paypal": "PayPal",
  "product.add_to_cart": "Add to Cart",
  "product.details.description": "Description",
  "product.details.specifications": "Specifications",
  "product.details.title": "Product Details",
  promotional_message: "Limited time offer! Get {{discount}}% off",
  "review.placeholder": "Share your thoughts...",
  "review.rating.average": "Average",
  "review.rating.excellent": "Excellent",
  "review.rating.good": "Good",
  "review.rating.poor": "Poor",
  "review.rating.terrible": "Terrible",
  "review.title": "Write a Review",
  "search.no_results": "No results found for your search.",
  "search.placeholder": "Search for products...",
  "shipping.flat_rate": "Flat Rate Shipping: {{price}}",
  "shipping.free_shipping": "Free Shipping",
  "status.in_stock": "In Stock",
  "status.out_of_stock": "Out of Stock",
  "success.message": "Your request was successful!",
  "tutorial.step": "Step {{number}}: {{instruction}}",
  "upload.file": "Upload File",
  "user.profile.edit": "Edit Profile",
  "user.profile.picture": "Profile Picture",
  "user.profile.title": "Your Profile",
  "validation.invalid_email": "Please enter a valid email address.",
  "validation.password_mismatch": "Passwords do not match.",
  "validation.required_field": "This field is required.",
  "wishes.happy_birthday": "Happy Birthday, {{name}}!",
} satisfies HugeTranslations;
